<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\mono-addins.snk</AssemblyOriginatorKeyFile>
    <PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\bin</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <PackageId>Mono.Addins.Setup</PackageId>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS0618;SYSLIB0011;SYSLIB0050;SYSLIB0051</NoWarn>
  </PropertyGroup>
  <Import Project="..\Version.props" />
  <ItemGroup>
    <PackageReference Include="SharpZipLib" Version="1.2.0" />
    <ProjectReference Include="..\Mono.Addins\Mono.Addins.csproj" />
  </ItemGroup>
</Project>